[2023-08-23T09:15:14.282+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2023-08-23T09:10:11.043046+00:00 [queued]>
[2023-08-23T09:15:14.306+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2023-08-23T09:10:11.043046+00:00 [queued]>
[2023-08-23T09:15:14.309+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2023-08-23T09:15:14.346+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-08-23 09:10:11.043046+00:00
[2023-08-23T09:15:14.358+0000] {standard_task_runner.py:57} INFO - Started process 4610 to run task
[2023-08-23T09:15:14.366+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2023-08-23T09:10:11.043046+00:00', '--job-id', '13197', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpj8zexhp8']
[2023-08-23T09:15:14.370+0000] {standard_task_runner.py:85} INFO - Job 13197: Subtask create_postgres_table
[2023-08-23T09:15:14.468+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2023-08-23T09:10:11.043046+00:00 [running]> on host b0ce6883e4a1
[2023-08-23T09:15:14.601+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Techquier' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-08-23T09:10:11.043046+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-23T09:10:11.043046+00:00'
[2023-08-23T09:15:14.605+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-08-23T09:15:14.622+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-08-23T09:15:14.641+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-08-23T09:15:14.882+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "***"

[2023-08-23T09:15:14.897+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20230823T091011, start_date=20230823T091514, end_date=20230823T091514
[2023-08-23T09:15:14.916+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13197 for task create_postgres_table (connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "***"
; 4610)
[2023-08-23T09:15:14.941+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-23T09:15:14.973+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
